package com.github.Ukasz09.ticTacToeTDD.applicationLogic.eventObservers;


public enum EventKind {
    //Buttons
    SIGN_BUTTON_CLICKED, AVATAR_BUTTON_CLICKED, CHOSEN_VALID_NAME, START_BUTTON_CLICKED, BOARD_SIZE_CHOSEN, GAME_BOX_BUTTON_CLICKED,
    END_GAME_BUTTON_CLICKED, REPEAT_GAME_BUTTON
}
